variable "vpc_id" {}
variable "discovery_service" {}
variable "private_subnet_ids" {}
variable "ClusterName" {}
variable "JenkinsSecurityGroup" {}
variable "JenkinsAgentSecurityGroup" {}
variable "EFS_SecurityGroup" {}
variable "jenkins_password" {}
variable "JenkinsUsername" {}
variable "JenkinsJNLPPort" {}
variable "JenkinsURL" {}
variable "CloudwatchLogsGroup" {}
variable "CloudwatchLogsAgent" {}
variable "RegionName" {}
variable "ECSTaskRole" {}
variable "ECSExecutionRole" {}
variable "AccessPointResource" {}
variable "FileSystemResource" {}
variable "Namespace" {}
variable "LoadBalancerListenerHTTPS" {}
variable "JenkinsTargetGroup" {}